version:  '3.0'

services:
    rasa_notebook:
        image: bowenwen/rasa_chatbot_nb:latest
        networks: ['rasa-network']
        ports:
            - "8888:8888"
        volumes: # set your own {$PWD}
            - ./:/home/jovyan/work
        user: root
        environment:
            - GRANT_SUDO=yes 
            - NB_UID=1000
        command: jupyter notebook --allow-root --ip=0.0.0.0 --no-browser --notebook-dir=/home/jovyan/work --NotebookApp.password='sha1:8f3d668b74ed:9ec0b85bb0b353d733115ce17c7ae00a51d6518d'
        # default password: admintest
        container_name: rasa_notebook
        
    action_server:
        image: bowenwen/rasa_chatbot_nb:latest
        networks: ['rasa-network']
        ports:
            - "5055:5055"
        volumes:
            - ./:/home/jovyan/work
        command: python -m rasa_core_sdk.endpoint --actions actions
        container_name: action_server

networks: {rasa-network: {driver: bridge}}
            