version:  '3'

services:
    tcb_trainer:
        image: bowenwen/rasa_chatbot_nb:latest
        restart: always
        volumes: # set your own {$PWD}
            - /:/home/jovyan/transit_chatbot
        user: root
        environment:
            - GRANT_SUDO=yes 
            - NB_UID=1000
        container_name:   transit_chatbot_trainer
        command: jupyter notebook --allow-root --ip=0.0.0.0 --no-browser --notebook-dir=/home/jovyan/transit_chatbot --NotebookApp.password='sha1:8f3d668b74ed:9ec0b85bb0b353d733115ce17c7ae00a51d6518d'
        # default password: admintest
        networks:
            - tcb
        ports:
            - 8888:8888
        # unassigned ports: 49152 to 65535
            
networks:
  tcb:
    driver: bridge
            