
policies:
  - name: KerasPolicy
    epochs: 200
    max_history: 2
    validation_split: 0.2
    batch_size: 32
  - name: FallbackPolicy
    fallback_action_name: 'utter_garbage'
    core_threshold: 0.1
    nlu_threshold: 0.1
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
