facebook:
  verify: "rasa-bot"
  secret: "generate-your-own-secret"
  page-access-token: "obtain-your-own-page-access-token-from-facebook"
  
slack:
  slack_token: "enter-your-token"
  slack_channel: "@my_channel"
